version: 2.1

general:
  branches:
    only:
     - master
     - develop
     - /feature/.*/

references:
  defaults: &defaults
    working_directory: ~
    docker:
      - image: circleci/node:11.10.1-browsers
  update_npm: &update_npm
    run:
      name: "Update npm"
      command: 'sudo npm install -g npm@latest'
  install_node_modules: &install_node_modules
    run:
      name: "Install node modules"
      command: 'npm install'
  build: &build
    run:
      name: "Build module"
      command: "npm run build"
  test: &test
    run:
      name: "Test module"
      command: "npm run test"

jobs:
  build_test:
    <<: *defaults
    steps:
      - checkout
      - *update_npm
      - *install_node_modules
      - *build
      - *test

workflows:
  build_test:
    jobs:
      - build_test
